#create a matrix under build
#The Set up Python step should install python-version 3.7, 3.8, 3.9
# Use py-version as the key to define these python-version within the matrix.
# Modify the job and step to make use of these matrix values.

name: Installing Python

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12, windows-latest]
        py-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 4
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
